### ISSUE TITLE
Error when activating Application Search

### ISSUE THREAD

**Issue by pauLee** [oliverschwendener/ueli#308] opened 2020-03-06 11:39 UTC
I can not launch any application with Ueli and I get an error when activating or modifying the Application search.

The error:
{ "cmd": "mdfind \"kind:apps\" | egrep \"^\\/Applications\"", "code": 1, "killed": false, "level": "error", "service": "user-service", "signal": null, "timestamp": "2020-03-06T11:36:49.611Z" }
<img width="570" alt="Bildschirmfoto 2020-03-06 um 12 38 20" src="https://user-images.githubusercontent.com/592889/76080540-68c2de80-5fa7-11ea-8c67-fb3a9514527b.png">

I'am using Ueli version 8.5.3 on the latest Mac OS 10.15.3
[debug.log](https://github.com/oliverschwendener/ueli/files/4298104/debug.log)

**Comment by blmhemu** [comment] 2020-03-07 21:12
The bug : You probably might have disabled indexing which this app is using.
https://www.technipages.com/macos-sierra-enable-disable-spotlight

Solution : Try running `sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist`

**Comment by pauLee** [comment] 2020-03-08 11:21
Thank you for that idea but this wasn't the problem. The spotlight-index isn't disabled. I also tried to rebuild the index. Spotlight itself works very good.

**Comment by oliverschwendener** [comment] 2020-03-19 09:56
What happens if you reset the application search settings to default?

![image](https://user-images.githubusercontent.com/15727229/77054595-45992580-69d0-11ea-9a29-2bdcd99fde30.png)

**Comment by pauLee** [comment] 2020-03-19 10:03
The error still remains.

**Comment by oliverschwendener** [comment] 2020-03-19 10:06
What happens if you remove all folders in the settings?

**Comment by pauLee** [comment] 2020-03-22 02:09
The error disappears when I delete the last folder path. But it doesn't matter which path I remove last.
And the error does not occur if I disable and enable the plugin when all folders are deleted.

**Comment by dkanas** [comment] 2020-04-03 11:37
@oliverschwendener I might have found the issue:

I'm running mac OS 10.15.3 and running `mdfind kind:apps` in the terminal returns nothing, but when I run `mdfind apps` it seems to return a full list of apps.

**Comment by pauLee** [comment] 2020-04-03 15:50
> @oliverschwendener I might have found the issue:
> 
> I'm running mac OS 10.15.3 and running `mdfind kind:apps` or `mdfind "kind:apps"` in the terminal returns nothing, but when I run `mdfind kMDItemContentTypeTree=com.apple.application-bundle` it seems to return a full list of apps.

Yes, same for me!

**Comment by xfirf** [comment] 2020-05-06 06:11
I´ve just added the mentioned command in application-searcher.ts in line 39
`            executeCommandWithOutput(`mdfind kMDItemContentTypeTree=com.apple.application-bundle | egrep "${folderRegex}"`)
`

that improves the search but still does not show all applications. Outlook is working now but Mail (Apple Mail) is still missing.

Maybe the folderRegex has to be updated too.

**Comment by oliverschwendener** [comment] 2020-05-06 12:27
@xfirf Did you try adding `/System/Applications` to the application folders in the settings?

**Comment by xfirf** [comment] 2020-05-06 12:30
> @xfirf Did you try adding `/System/Applications` to the application folders in the settings?

Ah. Now it´s working as intended. (with the changed line mentioned above)
Thank you.

**Comment by oliverschwendener** [comment] 2020-05-06 12:50
@pauLee You still aren't able to find all applictions?

**Comment by pauLee** [comment] 2020-05-06 13:53
Yes, unfortunately the situation is still the same. I can't find any apps.

But I get another error:
Error: Command failed: mdfind "kind:apps" | egrep "^\/Applications|^\/System/Library/CoreServices|^\/Users/tom/Applications|^\/System/Applications/"

**Comment by pthoelken** [comment] 2020-06-04 15:22
When will this fix merged to public and released? The error is thill there on my macOS.
 #372

**Comment by oliverschwendener** [comment] 2020-06-05 08:04
Before I consider #372 to really fix this problem I want to understand why & when the issue occurs. Unfortunately I can't find a pleasing documentation on how to use `mdfind` correctly.

For me it seems that `mdfind "kind:apps"` works just fine on macOS 10.14.x. Are you guys (those who experience this issue) using macOS 10.15.x?

**Comment by xfirf** [comment] 2020-06-05 08:08
> Before I consider #372 to really fix this problem I want to understand why & when the issue occurs. Unfortunately I can't find a pleasing documentation on how to use `mdfind` correctly.
> 
> For me it seems that `mdfind "kind:apps"` works just fine on macOS 10.14.x. Are you guys (those who experience this issue) using macOS 10.15.x?

Yes, I´m on OSX 10.15.x

**Comment by pauLee** [comment] 2020-06-05 08:09
> Before I consider #372 to really fix this problem I want to understand why & when the issue occurs. Unfortunately I can't find a pleasing documentation on how to use `mdfind` correctly.
> 
> For me it seems that `mdfind "kind:apps"` works just fine on macOS 10.14.x. Are you guys (those who experience this issue) using macOS 10.15.x?

Yes, I'am on Mac OS 10.15.x too.

**Comment by pthoelken** [comment] 2020-06-05 08:16
Yes, I'am on Mac OS 10.15.x too.

**Comment by oliverschwendener** [comment] 2020-06-05 08:18
So to me it looks like these are the correct ways to retreive apps:

- macOS 10.14.x and older: `mdfind "kind:apps"`
- macOS 10.15 and newer: `mdfind kMDItemContentTypeTree=com.apple.application-bundle`

Can you guys confirm this?

**Comment by pthoelken** [comment] 2020-06-05 08:23
`mdfind kMDItemContentTypeTree=com.apple.application-bundle` 
works for me in macOS 10.15.5
`mdfind "kind:apps"`
didn't work

**Comment by pauLee** [comment] 2020-06-05 08:47
> `mdfind kMDItemContentTypeTree=com.apple.application-bundle`
> works for me in macOS 10.15.5
> `mdfind "kind:apps"`
> didn't work

Same for me!

**Comment by oliverschwendener** [comment] 2020-06-05 09:05
What are you guys getting when executing this: `mdfind "kind:preferences"` ?

**Comment by pauLee** [comment] 2020-06-05 09:17
> What are you guys getting when executing this: `mdfind "kind:preferences"` ?

Nothing.

**Comment by oliverschwendener** [comment] 2020-06-06 23:25
Then this needs to be updated too. But let's create a separate issue for that.

**Closed** 2020-06-08 20:45 UTC
Labels: bug

**Comment by stefarossi** [comment] 2020-09-11 23:49
I'm encountering this error on 10.13.6. `mdfind "kind:apps"` returns nothing, while `mdfind kMDItemContentTypeTree=com.apple.application-bundle` works as expected and returns a huge list of apps.

**Comment by gregsadetsky** [comment] 2020-11-09 21:14
I doubt anybody will have the same issue, but I was also having the "mdfind" errors under 10.15. In my case, this is because in System Preferences, under Spotlight, in the "Privacy" tab, I had setup Spotlight to not index a list of directories which ended up containing the applications directory I wanted to have indexed by ueli.

Thank you!

**Comment by JanKreuzer** [comment] 2022-02-03 07:57
Im on MacOS 10.14.6 and on Ueli 8.19.0 and in 2022 i still have the same issue

**Comment by pthoelken** [comment] 2022-02-03 08:01
> Im on MacOS 10.14.6 and on Ueli 8.19.0 and in 2022 i still have the same issue

Did you try to upgrade macOS to v12?

**Comment by JanKreuzer** [comment] 2022-02-03 08:03
what du you mean with v12? Big Sur?

**Comment by pthoelken** [comment] 2022-02-03 08:04
No. The latest version of macOS (Monterey) ... how old is your macbook?

**Comment by JanKreuzer** [comment] 2022-02-03 08:06
i can not upgrade because i need 32 bit support for work and mac os Mojave is the latest mac os with 32 bit support.

**Comment by pthoelken** [comment] 2022-02-03 08:09
Mojave is  EOL by Apple. I don't think that @oliverschwendener supports here for a EOL OS version. Bad situation for you.

**Comment by JanKreuzer** [comment] 2022-02-03 08:13
Thanks for the help
