### ISSUE TITLE
"opera browser" to Browser Bookmarks "windows system"

### ISSUE THREAD

**Issue by mragtronx8** [oliverschwendener/ueli#804] opened 2021-09-18 19:12 UTC
kind reminder 
please add "opera browser" to Browser Bookmarks "windows system"

_Originally posted by @mragtronx8 in https://github.com/oliverschwendener/ueli/issues/654#issuecomment-922354857_

**Comment by oliverschwendener** [comment] 2021-09-19 08:16
Closing this because it's a duplicate of #654

**Closed by oliverschwendener** 2021-09-19 08:16 UTC
