### ISSUE TITLE
ueli input window moves while typing

### ISSUE THREAD

**Issue by jonhil** [oliverschwendener/ueli#37] opened 2018-06-27 12:17 UTC
When typing in the ueli input window the window moves.
With every input keystroke the ueli window moves up and left.

Start:
![ueli_1](https://user-images.githubusercontent.com/11158762/41973195-9768bc0c-7a14-11e8-9166-141743226316.jpg)
Result:
![ueli_2](https://user-images.githubusercontent.com/11158762/41973199-98e56832-7a14-11e8-8d0a-9354a91a511b.jpg)

Expected behavior:
A not moving input window ;)

ueli 4.7.0
Windows 10 Education N 1803

**Comment by oliverschwendener** [comment] 2018-06-27 13:20
Haha wtf, I have never seen this before and I have litterally no idea what it could be. 😅  I can't reproduce your bug. Can you clone the repo and start ueli from the command line ([instructions](https://github.com/oliverschwendener/ueli#setup))? Maybe there is a clue in the console logs.

**Comment by LevinFaber** [comment] 2018-07-09 11:31
Same problem, Win10 Pro, latest release. Will add console logs if I get the time.

**Comment by oliverschwendener** [comment] 2018-07-11 05:07
Maybe there is a bug when placing the window. Try to set `alwaysShowOnPrimaryDisplay` to `true` in the config file (`~/ueli.config.json`).

**Comment by jonhil** [comment] 2018-07-12 10:36
I tried to set `alwaysShowOnPrimaryDisplay` to `true`  and restartet ueli but it didn't change the inputwindow movement.
I also cloned the repo and startet ueli from the command line but the bug still existed and there was no info or error in the console. Or is there defined logging location?

**Comment by oliverschwendener** [comment] 2018-07-12 10:46
At the moment there is only console logging.

**Comment by jonhil** [comment] 2018-07-12 12:58
Ok. Then this is all I got from the console:
`λ yarn start`
`yarn run v1.7.0`
`$ ./node_modules/.bin/electron . --enable-logging`
`Batchvorgang abbrechen (J/N)? j`

I opened multiple programs but the movement bug was consistent. Sorry for not having more info.

**Comment by oliverschwendener** [comment] 2018-07-20 14:50
Unfortunately I have no clue what it could be 😢

**Comment by khanhas** [comment] 2018-08-28 17:58
I found the cause. If you set this value > 100%, Ueli starts to move when typing:
![image](https://user-images.githubusercontent.com/26436809/44741236-ae872700-ab26-11e8-8a71-b6319be0d783.png)

**Comment by oliverschwendener** [comment] 2018-08-29 08:59
@khanhas Thank you for your research! 
To be more precise: if you set the custom scaling value to a value that is not listed here...

![image](https://user-images.githubusercontent.com/15727229/44777258-6f82c100-ab7a-11e8-8ec6-fa4bfa5ce52c.png)

...the window starts moving while typing.

@jonhil & @LevinFaber Did you set a custom scaling in Windows?

**Comment by oliverschwendener** [comment] 2018-09-01 06:28
I added this to [known bugs](https://github.com/oliverschwendener/ueli#known-bugs).

**Comment by jonhil** [comment] 2018-09-03 21:09
@oliverschwendener oh yeah I used a custom value there and forgot to set it back :P 
changed it to 100% and everything is working perfekt again 👍 thanks!

**Comment by oliverschwendener** [comment] 2018-09-03 21:13
Allright! I am closing this issue because this seems to be a bug in chromium or electron. Once again, big thanks to @khanhas for the research!

**Closed by oliverschwendener** 2018-09-03 21:13 UTC
Labels: bug

**Comment by Zangoran** [comment] 2019-08-22 02:43
I am having this issue still. Is there any way that you guys can hardcode the app to not move? I need to have to the custom scaling to actually see my laptop screen and not to have it super big.

**Comment by Zangoran** [comment] 2019-09-01 00:38
@oliverschwendener Any thoughts on my last comment?

**Comment by oliverschwendener** [comment] 2019-09-13 18:54
@Zangoran I'm sorry, at the moment there is nothing I can do because this is a bug in electron/chromium.

**Comment by Zangoran** [comment] 2019-09-13 19:20
@oliverschwendener This might be a stretch, but is there a way where you can add an option to hardcode the x and y value as a setting so it can't move?

**Comment by oliverschwendener** [comment] 2019-09-17 16:02
As I said this is a bug of electron/chromium. The window starts to move even if I hardcode the app not to move. Even Windows itself recommends not using custom scaling so I guess you have to find another solution because there is nothing I can do.

**Comment by waqashsn** [comment] 2020-03-28 11:16
A workaround to this issue is to turn on "Remember window position" in settings. This stops the window from moving around when custom scaling is set.

**Comment by stefnotch** [comment] 2020-06-03 13:10
Which Electron/Chrome bug is the relevant one so that we can vote on it?

Also, the workaround by waqashsn works beautifully well.

**Comment by laxu** [comment] 2020-10-22 20:28
Experiencing this bug as well. Turning on "Remember window position" does not seem to fix the issue. Haven't seen this in any other Electron app either.

**Comment by oliverschwendener** [comment] 2020-10-23 12:19
@laxu Do you have custom UI scaling activated in Windows?

**Comment by laxu** [comment] 2020-10-23 15:59
> @laxu Do you have custom UI scaling activated in Windows?

I do, 120% custom scaling.

**Comment by oliverschwendener** [comment] 2020-10-24 10:35
I don't know if there is a bug report for this on electron yet.

Here is what I tested on electron 10.1.4:

``` typescript
import { app, BrowserWindow } from "electron";
import { join } from "path";

let browserWindow: BrowserWindow | null;

app.on("ready", startApp);
app.on("window-all-closed", () => app.quit());

function startApp() {
    createBrowserWindow();
}

function createBrowserWindow() {
    browserWindow = new BrowserWindow({
        webPreferences: {
            nodeIntegration: true,
        },
    });
    browserWindow.loadFile(join(__dirname, "..", "views", "main.html"));

    setInterval(() => repositionWindow(), 1000);
}

function repositionWindow() {
    if (browserWindow) {
        browserWindow.center();
    }
}
```

I created an empty app that repositions the window every second on the center of the screen by calling `center()` method on the `BrowserWindow`. And everytime this happens the window starts to move. This only happens if a custom scaling value is set. So I guess this is a bug on electron's side.

**Comment by oliverschwendener** [comment] 2020-10-24 10:39
Ok I just managed to reproduce this issue even without custom UI scaling.

**Comment by oliverschwendener** [comment] 2020-10-24 10:40
Let's track this issue here: #515
