### ISSUE TITLE
[Bug] Currency conversion does not work

### ISSUE THREAD

**Issue by KataLoved** [oliverschwendener/ueli#1111] opened 2024-06-10 08:02 UTC
Currency conversion stopped working, and resetting/reinstalling the app doesn't work.

**Screenshots**
![image](https://github.com/oliverschwendener/ueli/assets/54185009/47a55638-7cf0-485a-ac93-dae2335595d0)

**Debug Logs**
```log
2024-06-10T07:43:16.228Z debug: Update check result: update not available
2024-06-10T07:43:29.690Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
2024-06-10T07:43:44.987Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
2024-06-10T07:45:59.938Z debug: Skipping app icon generation. All app icons already exist
2024-06-10T07:45:59.942Z debug: Successfully refreshed all indexes
2024-06-10T07:47:44.300Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
2024-06-10T07:51:00.131Z debug: Skipping app icon generation. All app icons already exist
2024-06-10T07:51:00.135Z debug: Successfully refreshed all indexes
2024-06-10T07:53:04.516Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
2024-06-10T07:53:10.379Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
2024-06-10T07:53:14.458Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
2024-06-10T07:53:15.006Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
2024-06-10T07:53:20.989Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
2024-06-10T07:53:22.891Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
2024-06-10T07:55:59.912Z debug: Skipping app icon generation. All app icons already exist
2024-06-10T07:55:59.915Z debug: Successfully refreshed all indexes
2024-06-10T07:56:01.805Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
2024-06-10T07:56:07.543Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
2024-06-10T07:59:38.017Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404
```

**Environment**
 - OS: Windows 10
 - Version 22H2 (Build OS: 19045.2673)

**Comment by oliverschwendener** [comment] 2024-06-10 08:12
Duplicate of #1099

**Comment by oliverschwendener** [comment] 2024-06-10 08:12
This will be fixed with ueli v9

**Closed by oliverschwendener** 2024-06-10 08:12 UTC
Labels: bug
