### ISSUE TITLE
Dictionary search doesn't function - certificate issues?

### ISSUE THREAD

**Issue by megazver** [oliverschwendener/ueli#867] opened 2022-01-24 13:28 UTC
Fresh Windows 10 Pro 21H2 install, ueli version 8.19.0. The dictionary plugin turned on with default settings.

After you type in 'dict?', whatever you type after that just results in this:

![image](https://user-images.githubusercontent.com/9657370/150791256-8831a174-5572-4583-91fb-1b54115a37f0.png)

The log just has this error message in it:

`2022-01-24T13:25:10.489Z error: certificate has expired`

**Comment by oliverschwendener** [comment] 2022-01-24 13:50
Thanks for reporting, I think this is a duplicate of #807

**Closed by oliverschwendener** 2022-01-24 13:50 UTC
