### ISSUE TITLE
[Feature Request] As a new user of ueli, I would like to use control + windows key as "hot key"

### ISSUE THREAD

**Issue by joost00719** [oliverschwendener/ueli#353] opened 2020-04-22 10:30 UTC
Hi,

I am a new user of ueli. Before ueli I just used the windows key and started typing.
I do like ueli far better than the Windows search, but I catch myself using the windows search most of the time anyways. It would be a great addition to add the windows key as an option to set your hot key.
For mac this would be command obviously.

**Comment by ClementNerma** [comment] 2020-04-22 15:38
I agree, I find it most intuitive to use these two keys to run the program 👍

**Comment by themegaphoenix** [comment] 2020-05-05 22:12
unfortunately this is not possible due to electron only allowing multiple modifiers followed by a single keycode
to solve this we could have control + windows key + anyother key
see this:
https://www.electronjs.org/docs/api/accelerator
i will add the option to select the windows key

**Comment by ClementNerma** [comment] 2020-05-05 23:05
> unfortunately this is not possible due to electron only allowing multiple modifiers followed by a single keycode
> to solve this we could have control + windows key + anyother key
> see this:
> https://www.electronjs.org/docs/api/accelerator
> i will add the option to select the windows key

But it would be great to *at least* be able to set any `CmdCtrl+Alt+<key>` combination, allowing to trigger Ueli with another shortcut through an AutoHotKey script for instance.

**Comment by joost00719** [comment] 2020-05-06 08:34
> > unfortunately this is not possible due to electron only allowing multiple modifiers followed by a single keycode
> > to solve this we could have control + windows key + anyother key
> > see this:
> > https://www.electronjs.org/docs/api/accelerator
> > i will add the option to select the windows key
> 
> But it would be great to _at least_ be able to set any `CmdCtrl+Alt+<key>` combination, allowing to trigger Ueli with another shortcut through an AutoHotKey script for instance.

Good thinking. Maybe it would be possible to use AutoHotKey to remap ctrl+winkey to alt+space.
I'll try to create a script after my work shift and share it here if I get it to work.

On a side note, ahk *could* be used in this app to allow windows key in UELI. But I think the user should be aware of that when setting the hotkey on winkey+someOtherKey AHK is being used. However, I don't think this is a very elegant solution and should be considered as a very dirty hack.

**Comment by themegaphoenix** [comment] 2020-05-06 09:31
> > unfortunately this is not possible due to electron only allowing multiple modifiers followed by a single keycode
> > to solve this we could have control + windows key + anyother key
> > see this:
> > https://www.electronjs.org/docs/api/accelerator
> > i will add the option to select the windows key
> 
> But it would be great to _at least_ be able to set any `CmdCtrl+Alt+<key>` combination, allowing to trigger Ueli with another shortcut through an AutoHotKey script for instance.

i think using `CmdCtrl+Alt+<key>` is already possible
however, the plus button in the settings does not seem to working for me
anyone else can confirm this?

**Comment by joost00719** [comment] 2020-05-06 09:34
> > > unfortunately this is not possible due to electron only allowing multiple modifiers followed by a single keycode
> > > to solve this we could have control + windows key + anyother key
> > > see this:
> > > https://www.electronjs.org/docs/api/accelerator
> > > i will add the option to select the windows key
> > 
> > 
> > But it would be great to _at least_ be able to set any `CmdCtrl+Alt+<key>` combination, allowing to trigger Ueli with another shortcut through an AutoHotKey script for instance.
> 
> i think using `CmdCtrl+Alt+<key>` is already possible
> however, the plus button in the settings does not seem to working for me
> anyone else can confirm this?

Confirmed. Doesn't work for me too. (I used the numpad so I didn't need to use shift key)

**Comment by themegaphoenix** [comment] 2020-05-06 09:44
> > > > unfortunately this is not possible due to electron only allowing multiple modifiers followed by a single keycode
> > > > to solve this we could have control + windows key + anyother key
> > > > see this:
> > > > https://www.electronjs.org/docs/api/accelerator
> > > > i will add the option to select the windows key
> > > 
> > > 
> > > But it would be great to _at least_ be able to set any `CmdCtrl+Alt+<key>` combination, allowing to trigger Ueli with another shortcut through an AutoHotKey script for instance.
> > 
> > 
> > i think using `CmdCtrl+Alt+<key>` is already possible
> > however, the plus button in the settings does not seem to working for me
> > anyone else can confirm this?
> 
> Confirmed. Doesn't work for me too. (I used the numpad so I didn't need to use shift key)

Issue number #170 does also support that the functionality was removed
using autohotkey is an alternative
if you wish to use the source code and modify to achieve this as well it can be done, but it would be hard coded
To do this, just modify this file:
[https://github.com/oliverschwendener/ueli/blob/master/src/common/global-hot-key/global-hot-key-modifier.ts](url)
by adding ` Alt+Control = "Alt+Control"` and building the application

**Comment by scapoor** [comment] 2020-06-05 20:55
> > > > > unfortunately this is not possible due to electron only allowing multiple modifiers followed by a single keycode
> > > > > to solve this we could have control + windows key + anyother key
> > > > > see this:
> > > > > https://www.electronjs.org/docs/api/accelerator
> > > > > i will add the option to select the windows key
> > > > 
> > > > 
> > > > But it would be great to _at least_ be able to set any `CmdCtrl+Alt+<key>` combination, allowing to trigger Ueli with another shortcut through an AutoHotKey script for instance.
> > > 
> > > 
> > > i think using `CmdCtrl+Alt+<key>` is already possible
> > > however, the plus button in the settings does not seem to working for me
> > > anyone else can confirm this?
> > 
> > 
> > Confirmed. Doesn't work for me too. (I used the numpad so I didn't need to use shift key)
> 
> Issue number #170 does also support that the functionality was removed
> using autohotkey is an alternative
> if you wish to use the source code and modify to achieve this as well it can be done, but it would be hard coded
> To do this, just modify this file:
> [https://github.com/oliverschwendener/ueli/blob/master/src/common/global-hot-key/global-hot-key-modifier.ts](url)
> by adding ` AltControl = "Alt+Control"` and building the application
> i have not tested this yet
---

I tested "AltControl" and it doesn't work. Since the [Electron JS accelerator mentions this](https://www.electronjs.org/docs/api/accelerator)
> Accelerators are Strings that can contain multiple modifiers and a single key code, combined by the + character, and are used to define keyboard shortcuts throughout your application."

I decided to play with it a little bit and was able to modify the code and got it working. We can have multiple key combinations (My fav. Ctrl+Alt+Space). But any combination of available modifiers can be used (except the combinations causing duplication for first and second modifier, which simply means the second modifier is useless).

As for the `Plus key`, it has to be pressed with `Shift`. For using the `NumPad +`, the code is `numadd` instead of `Plus`. (added in the patch as well)

I just wanted to test a theory so attempted it in a very small time. I am adding the diff patch. [Don't judge the coding, even if it's a lot of copying code].
Didn't modify the GUI or add the logic to prevent duplication of Modifiers (which when happens doesn't cause any issues).

[MultipleModifierPatchandPlusKey.txt](https://github.com/oliverschwendener/ueli/files/4738447/MultipleModifierPatchandPlusKey.txt)

**Comment by oliverschwendener** [comment] 2024-06-12 15:21
Duplicate of #454

**Closed by oliverschwendener** 2024-06-12 15:21 UTC
Labels: feature request
