### ISSUE TITLE
Dictionary Plugin showing 'an error occured when searching any word'

### ISSUE THREAD

**Issue by yannishamzed** [oliverschwendener/ueli#841] opened 2021-11-22 16:12 UTC
i just installed ueli and i just cant use the dictionary plugin. I have tried using a custom prefix but that doesn't solve it.
![image](https://user-images.githubusercontent.com/94152318/142895529-a630c2ee-057d-48a5-81a4-61dbdbd2d63d.png)

**Comment by oliverschwendener** [comment] 2021-11-22 16:17
I guess this is a duplicate of #807

**Closed by oliverschwendener** 2021-11-22 16:17 UTC
Labels: bug
