### ISSUE TITLE
Freezed search bar

### ISSUE THREAD

**Issue by hosseinzamaninasab** [oliverschwendener/ueli#571] opened 2020-11-14 22:14 UTC
When I open ueli, it will freeze and shows nothing.
![ueli_error](https://user-images.githubusercontent.com/70825061/99158069-07314300-26e4-11eb-98bf-00d90688524a.png)

**Comment by GovindKrishnan** [comment] 2020-11-15 02:54
It's due to Refreshing of Index. If you have enabled periodical rescan, this will happen in the set interval of time. Currently, Ueli doesn't accept input while it's refreshing due to some technical limitations. @oliverschwendener might fix it in future.

**Comment by oliverschwendener** [comment] 2020-11-17 06:37
Closing this because it's a duplicate of #562

**Closed by oliverschwendener** 2020-11-17 06:37 UTC
