### ISSUE TITLE
Everything plugin returns error when file path contains a special character

### ISSUE THREAD

**Issue by FRLHD** [oliverschwendener/ueli#369] opened 2020-05-06 10:38 UTC
I installed Ueli on my laptop as it looked better than what I was currently using and it allowed me to use Everything search. Sadly, everytime I try to use the Everything plugin, an error saying that it could not find the file pops up when I select a file path that contains a special character or even just an accent (characters like: à,è,é)

Any tips on how to solve?

**Comment by oliverschwendener** [comment] 2020-05-06 11:39
I think this is a duplicate of #175

**Closed by oliverschwendener** 2020-05-06 11:39 UTC
