### ISSUE TITLE
Removing Web Search Prefixes Disables Other Plugins

### ISSUE THREAD

**Issue by moses-bowman** [oliverschwendener/ueli#188] opened 2019-09-04 03:43 UTC
Since the 8.0.0 release, removing `Fallback Web search` _Prefixes_ 'bricks' other plugins such as `Calculator`, `Commandline`, `Currency Converter`, `Email`, and `URL` (at least from my end as these are the only ones I have enabled apart from `Web search`).

![image](https://user-images.githubusercontent.com/40249465/64224176-255cba00-cf09-11e9-9a06-33361de64abf.png)

![image](https://user-images.githubusercontent.com/40249465/64224015-93ed4800-cf08-11e9-854d-b4c1012a31af.png)
![image](https://user-images.githubusercontent.com/40249465/64224021-9a7bbf80-cf08-11e9-9351-88056101fbb3.png)
![image](https://user-images.githubusercontent.com/40249465/64224095-dd3d9780-cf08-11e9-894c-1c275b16445a.png)
![image](https://user-images.githubusercontent.com/40249465/64224087-d57df300-cf08-11e9-9c2b-2f5d9f27eb11.png)
![image](https://user-images.githubusercontent.com/40249465/64224115-f0e8fe00-cf08-11e9-80aa-3366c1cf0510.png)

EDIT: ~Version 8.0 Beta Release (#142) didn't have this issue.~ Version 7.2.5 didn't have this issue.

**Comment by oliverschwendener** [comment] 2019-09-04 06:51
You didn't specify a prefix for the web search engines. This is why they always show up.

**Comment by moses-bowman** [comment] 2019-09-04 08:34
Below are some screenshots of version 7.2.5
As seen on the second pic, no _Prefixes_ were specified, but they work well as `Fallback` searches along with other plugins.

![image](https://user-images.githubusercontent.com/40249465/64238481-14c03a00-cf31-11e9-920d-8d90f1664286.png)

![image](https://user-images.githubusercontent.com/40249465/64238716-84362980-cf31-11e9-95e8-924038483ac0.png)

![image](https://user-images.githubusercontent.com/40249465/64238737-8e582800-cf31-11e9-81a1-325c11bba7c2.png)

![image](https://user-images.githubusercontent.com/40249465/64238776-9d3eda80-cf31-11e9-9424-29d75d3c1026.png)

![image](https://user-images.githubusercontent.com/40249465/64238805-a92a9c80-cf31-11e9-833d-7d9a92b254ee.png)

![image](https://user-images.githubusercontent.com/40249465/64238824-b0ea4100-cf31-11e9-9270-1e8337291d80.png)

![image](https://user-images.githubusercontent.com/40249465/64238837-b6e02200-cf31-11e9-9bc8-f1e4f9bdcbf9.png)

**Comment by oliverschwendener** [comment] 2019-09-05 07:12
Yes I see that this worked in the old version. But in 8.x.x you have to specify a prefix for a web search engine (otherwise it will always show up). If you enable the `Fallback` option then the web search engine will show up if there are no other search results found.

**Comment by oliverschwendener** [comment] 2019-09-18 06:55
Closing this now because it is intended behavior.

**Closed by oliverschwendener** 2019-09-18 06:55 UTC
Labels: bug
