### ISSUE TITLE
Issue: Browser bookmarks, Solutions: add custom location field

### ISSUE THREAD

**Issue by HackerGprat** [oliverschwendener/ueli#992] opened 2023-02-24 16:56 UTC
**Issue :** 

error image
![image](https://user-images.githubusercontent.com/41012110/221238838-139f1e57-49c6-4ffc-80e5-a8f9cf80b5a5.png)

<hr>

**The bookmark files is here in this location** 
C:\Users\HackerGprat\AppData\Local\Google\Chrome\User Data\Profile 2

**Solutins :** the custom location filed required

Add Location of your bookmarks of your browser : [   __________  ]

**Comment by oliverschwendener** [comment] 2024-05-14 18:56
Duplicate of #628

**Closed by oliverschwendener** 2024-05-14 18:56 UTC
Labels: bug
