### ISSUE TITLE
Korean input is truncated.

### ISSUE THREAD

**Issue by plztrial4me** [oliverschwendener/ueli#938] opened 2022-07-18 01:53 UTC
I love this app, thanks for your work!

While testing this app, I found an error related to Korean input.
As you can see below, I entered two letters, but only one is recognized.

Is this a bug? or Are there any options to fix this issue?

![korean](https://user-images.githubusercontent.com/48973340/179434803-0f07ce58-dafb-4016-9498-cbf163ca44c2.gif)

![korean](https://user-images.githubusercontent.com/48973340/179434837-83f03c8f-0054-4029-8725-95ea52cfebff.png)

**Comment by oliverschwendener** [comment] 2022-11-02 10:26
I'll close this issue as it is most likely a duplicate of #665.

**Closed by oliverschwendener** 2022-11-02 10:26 UTC
