### ISSUE TITLE
Ueli command bar floats top-left on text imput

### ISSUE THREAD

**Issue by wooshaq** [oliverschwendener/ueli#1021] opened 2023-06-27 20:27 UTC
I just switched from my laptop to pc and want to continue to use ueli but on every key entry the command bar seems to move one pixel up and left. I never experienced something like this before.

**Comment by tkohlmeier** [comment] 2023-06-27 21:30
This is probably a duplicate of #515.

**Comment by oliverschwendener** [comment] 2023-06-28 07:57
Closing because this is a duplicate.

**Closed by oliverschwendener** 2023-06-28 07:57 UTC
