### ISSUE TITLE
[Feature Request] Bookmark Support for Chrome Beta

### ISSUE THREAD

**Issue by siddarththiru** [oliverschwendener/ueli#617] opened 2021-01-06 09:10 UTC
Right now only a few browsers seem to have support and chrome beta isn't one of them, since chrome is already supported, it wouldn't be hard to bring support for Chrome Beta, I hope the next update brings this feature, thanks.

**Comment by oliverschwendener** [comment] 2024-06-12 15:05
Duplicate of #622

**Closed by oliverschwendener** 2024-06-12 15:05 UTC
Labels: feature request
