### ISSUE TITLE
Bug when using ueli as a google search

### ISSUE THREAD

**Issue by CoinAxe** [oliverschwendener/ueli#709] opened 2021-04-25 19:31 UTC
When using ueli just for google search. sometimes the last letter doesn't show, another occasion a whole word didn't show

![image](https://user-images.githubusercontent.com/65632488/116006870-bf5d0300-a615-11eb-9eb8-cf0c3de636db.png)

**Comment by oliverschwendener** [comment] 2021-04-25 19:46
Duplicate of #665

**Closed by oliverschwendener** 2021-04-25 19:46 UTC
