### ISSUE TITLE
[bug]DuckDuckGo web search cut off search query

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#699] opened 2021-04-19 07:44 UTC
As you can see in the screenshot, ueli is suggesting different DuckDuckGo search queries than I have typed in. It does not happen with Google or Youtube.
![Screenshot_1](https://user-images.githubusercontent.com/43962138/115198918-e76ad480-a0f2-11eb-883d-8ac38a044eac.jpg)

**Comment by oliverschwendener** [comment] 2021-04-19 08:33
I guess this is related to #665

**Comment by oliverschwendener** [comment] 2021-04-25 19:47
I am going to close this issue because it's most likely a duplicate of #665

**Closed by oliverschwendener** 2021-04-25 19:47 UTC
Labels: bug
