### ISSUE TITLE
Super+Space combination not working on Windows 10

### ISSUE THREAD

**Issue by ghost** [oliverschwendener/ueli#609] opened 2020-12-21 20:10 UTC
As the title suggests, due to overlapping with the windows keyboard layout switch binding, the setting does not seem to have any effect. Tried to work around it with AutoHotkey to no avail. Curious if something on Ueli's end can be done about it.

**Comment by rluvaton** [comment] 2020-12-27 19:12
https://github.com/microsoft/PowerToys been able to override it

**Comment by DaProSkillz** [comment] 2021-01-30 15:11
Having the same issue here.

**Comment by nafarinha** [comment] 2021-03-22 08:48
> [PowerToys](https://github.com/microsoft/PowerToys) been able to override it

Please could you elaborate? Are you using the keyboard manager from PowerToys? Are you assigning a single key to the combo that opens Ueli? How did you specify the Super key, I don't see it on the drop down list?

**Comment by rluvaton** [comment] 2021-03-22 20:53
> > [PowerToys](https://github.com/microsoft/PowerToys) been able to override it
> 
> 
> 
> Please could you elaborate? Are you using the keyboard manager from PowerToys? Are you assigning a single key to the combo that opens Ueli? How did you specify the Super key, I don't see it on the drop down list?


I meant that PowerToys did that so for implementation, someone who want to create a PR can look there how it was done

**Comment by oliverschwendener** [comment] 2021-08-11 13:08
Is this a duplicate of #454 ?

**Closed** 2024-04-20 09:19 UTC
