### ISSUE TITLE
[Bugs] Browser search can't keep up with typing

### ISSUE THREAD

**Issue by fourteen-1** [oliverschwendener/ueli#778] opened 2021-08-05 10:54 UTC
I typed an 8 letter word, ueli just registered 1 letter.
![7osnGoOIN4](https://user-images.githubusercontent.com/73333396/128337360-6ca3d57e-c395-4727-9758-7be193a6808a.gif)

Browser search plugin doesnt register the whole of what I type. In order for it to properly work I have to slowly type, even then sometimes it will have a bug where some letters will not register, for example:

![NVIDIA_Share_ygZT42dc1a](https://user-images.githubusercontent.com/73333396/128338227-e939db6a-5f78-4663-a36e-6f4bee3d28eb.png)
In this case ueli didnt register the last 6 letters of the search. Sometimes this will happen to be the letters in the middle, or beginning; it is random but mostly happens to the last letters.

These bugs are really hampering with my productivity, please fix them.

Thanks.

**Comment by oliverschwendener** [comment] 2021-08-05 11:46
I think this is a duplicate of #665?

**Comment by fourteen-1** [comment] 2021-08-05 13:22
> 
> 
> I think this is a duplicate of #665?


The search and typing delay would be a duplicate. 

But what about the random exclusion of letters within the searched term? Ueli sometimes doesn't recognize portions of the text inputted even before hitting enter and initiating the browser as shown in the second screenshot, i've just typed the search term "incident" and waited, but ueli only recognized "in" for some reason which is defintely not caused for typing-search delay?

**Comment by oliverschwendener** [comment] 2021-08-05 14:29
I think it is caused by the same issue. By the time ueli fetched the search suggestions you already continued typing and the search results are not matching your search term anymore.

**Comment by firinael** [comment] 2021-08-30 15:33
Could this be remedied by the first item not being treated as a suggestion and just as a straight-up search shortcut? As in, if it doesn't have to fetch anything from the server, it could just search directly by inputting the terms entered into the query link placeholder spaces and therefore wouldn't suffer from a delay (at least not from ueli's part), no?

Not sure if it's feasible but ¯\_(ツ)_/¯

**Closed** 2021-09-07 05:56 UTC
Labels: bug
