### ISSUE TITLE
Strange search

### ISSUE THREAD

**Issue by Bob-dot360** [oliverschwendener/ueli#573] opened 2020-11-15 05:33 UTC
In my Explorer I [disable left menu](https://i.imgur.com/pkC6Dgz.png), but when I search something with Everything or Simple folder search plugin, Explorer launch [with it](https://i.imgur.com/HBBrPbg.png). Thank you for your work. Ueli became almost perfect except this thing and few little bugs

**Comment by AmrBinBashir** [comment] 2020-11-15 21:14
Duplicate of #379 and #350

**Comment by Miha537** [comment] 2020-11-16 06:01
Just tried 8.5.0 and it works perfect, I didn't notice anything slow. But I can't use it because in this version Everything doesn't work correctly eith russian language

**Comment by oliverschwendener** [comment] 2024-05-14 18:04
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.

**Closed by oliverschwendener** 2024-05-14 18:04 UTC
Labels: bug
