### ISSUE TITLE
[Bug] Win + ↑ shortcut maximizes the launcher and messes up with the design of the application.

### ISSUE THREAD

**Issue by brunovzky** [oliverschwendener/ueli#1149] opened 2024-07-31 05:51 UTC
**Describe the bug**
It's possible to maximize the Ueli window with the Win + ↑ shortcut and when you do that, the next time you open the launcher again it will be all black, no blur.

**To Reproduce**
1. Open the launcher with your shortcut
![image](https://github.com/user-attachments/assets/ef5d139f-5b2f-45b8-b214-aba7fb6768c3)

2. Maximize with Win + ↑
![image](https://github.com/user-attachments/assets/581e041d-abdc-4b6f-a4c3-f8a8ed8094ee)

3. Close the launcher window and open again
![image](https://github.com/user-attachments/assets/2a7c747d-3d26-409f-ae87-d901a026a49c)

**Expected behavior**
In my opinion, it shouldn't be possible to resize the window, but if the devs decide to keep this way, I think the design of the window should at least remain the same.

**Screenshots**
In the ***To Reproduce*** steps

**Environment**
 - OS: Windows
 - Version 23H2 (0S Build 22631.3958)

**Additional context**
In my issue I only mentioned the Win + ↑ shortcut, but it is also possible to resize the launcher to half the screen with Win + → and Win + ←

However, the bug doesn't happen when we do this, only when we maximize the window.

**Comment by oliverschwendener** [comment] 2024-07-31 06:05
Duplicate of #1120

**Closed by oliverschwendener** 2024-07-31 06:05 UTC
Labels: bug
