### ISSUE TITLE
[Feature Request] Setting to open currently running app

### ISSUE THREAD

**Issue by MohamedElgharbawy** [oliverschwendener/ueli#984] opened 2023-01-27 18:29 UTC
Would it be possible to get a setting that opens the current instance of an app if it's already running? For example, if you have chrome open in the background and write chrome into the search bar, it will open a new window instead of the current one.

**Comment by oliverschwendener** [comment] 2023-01-28 18:38
Not sure about this but I think this is the responsibility of every application itself. Chrome for example opens a new window while Adobe Photoshop brings the currently running instance to the foreground.

**Comment by MohamedElgharbawy** [comment] 2023-01-28 20:30
It should be possible, this app seems to make it work: https://github.com/kvakulo/Switcheroo

**Comment by oliverschwendener** [comment] 2023-01-28 21:24
I'm not saying that it's impossible to bring the currently running instance to the foreground. But it's hard to distinguish between apps that can run more than one window instance, so it's hard to build a UI that offers both options "new instance" and "show currently running app".

**Comment by MohamedElgharbawy** [comment] 2023-01-28 21:34
Instead of figuring out the logic for multiple window instances, could this just be a setting that opens the currently running app if there is one, and if there's not, open a new instance (so only one window)?

**Comment by ironyman** [comment] 2023-02-16 03:35
Could you have a mode where it lists all the open windows and lets you switch between them? Like switcheroo mode?

**Comment by oliverschwendener** [comment] 2024-05-14 18:54
Closing this as it is a duplicate of #86

**Closed by oliverschwendener** 2024-05-14 18:54 UTC
Labels: feature request
