### ISSUE TITLE
Search engine shows less than the entered text if typed fast

### ISSUE THREAD

**Issue by Meharban-Singh** [oliverschwendener/ueli#687] opened 2021-04-08 17:46 UTC
![problem](https://user-images.githubusercontent.com/33323725/114072467-ed95c100-9867-11eb-81e5-e7dd7fa16f93.gif)

As in the gif attached, when I search something using the prefix '?', using the web search plugin, it only shows the first few characters of whatever I typed in. It should open the browser with all the content searched for. 

Example: Type "?github" and press enter in ueli search box (where ? is the prefix for web search plugin). It opens up the browser and on duckduckgo, searches for "gith" or something like that missing the last few characters. This does not happen if I wait 1 second after typing my search.

**Comment by oliverschwendener** [comment] 2021-04-08 18:10
This is a duplicate of #665

**Closed by oliverschwendener** 2021-04-08 18:10 UTC
