### ISSUE TITLE
Feature request: Kill/force quit applications/processes

### ISSUE THREAD

**Issue by johanhelsing** [oliverschwendener/ueli#382] opened 2020-05-12 06:13 UTC
Killing unresponsive applications requires a lot of clicks on windows, would be useful to be able to do this through ueli. i.e. `kill misbehavingapp`.

**Comment by oliverschwendener** [comment] 2020-05-12 06:20
Duplicate of #128

**Closed by oliverschwendener** 2020-05-12 06:20 UTC

**Comment by johanhelsing** [comment] 2020-05-12 06:31
Ah, sorry (tried searching issues for "kill" and "quit", but nothing showed up).
