### ISSUE TITLE
Having 3-5 second lag spikes while playing games

### ISSUE THREAD

**Issue by shaiz-o** [oliverschwendener/ueli#781] opened 2021-08-11 12:09 UTC
Tried everything and it turns out that ueli running in the background is the cause of this problem. I have a really low-end PC and that's maybe why I'm one of the only people experiencing this. I have to end of all of its processes to do something resource intensive. Looking for a solution.

**Comment by firinael** [comment] 2021-08-30 15:34
Have you inspected what resources are being bottlenecked when you have those lag spikes? Is it the RAM, CPU, GPU, or what?

**Comment by tkohlmeier** [comment] 2021-09-04 10:49
I think this is a duplicate of #719.

**Comment by oliverschwendener** [comment] 2024-02-16 20:08
Closing because of duplicate

**Closed by oliverschwendener** 2024-02-16 20:08 UTC
Labels: bug
