### ISSUE TITLE
A Javascript error occured in main process 

### ISSUE THREAD

**Issue by jygzyc** [oliverschwendener/ueli#517] opened 2020-09-15 07:28 UTC
when I input j and **[Tab]** in input blank, there occurs an error 
```txt
A JavaScript error occurred in the main process
Uncaught Exceptions
Error: Error while trying to autocomplete. No plugin found for the search result item at t.SearchEngine.autoComplete (C:\Program
Files\ueli\resources\app.asar\bundle\main,js:34: 125752)
at lpcMainlmpi<anonymous. (C:\Program
Files\ueli\resources\app.asar\bundle\main.js:1 9.8O288)
at IpcMainImpI.emt (events.js:210:5)
at WebContents. <anonymous> (electron/js2c/browser initjs:3908:1 5)
at WebContents.emit (events.js:21 0:5)
```

**Comment by jygzyc** [comment] 2020-09-15 07:30
ueli version: 8.8.2

**Comment by AmrBinBashir** [comment] 2020-09-15 18:00
@jygzyc  Can you provide a gif of the error ?
I'd recommend using this lite software https://www.screentogif.com

**Comment by jygzyc** [comment] 2020-09-23 01:48
@AmrBinBashir Sorry for seeing it so late. Then I will have a try

**Comment by jygzyc** [comment] 2020-09-23 02:05
> @AmrBinBashir Sorry for seeing it so late. Then I will have a try

![bug](https://user-images.githubusercontent.com/33087260/93956223-3aaabd80-fd84-11ea-8501-416859844581.gif)

**Comment by AmrBinBashir** [comment] 2020-09-23 02:14
@jygzyc I think I know what causes the issue. 
In the gif you sent me, I am guessing that first search result was flash-player which is a from control-panel plugin. 
I'll submit a PR to fix.

**Comment by jygzyc** [comment] 2020-09-23 02:17
> @jygzyc I think I know what causes the issue.
> In the gif you sent me, I am guessing that first search result was flash-player which is a from control-panel plugin.
> I'll submit a PR to fix.

Yes, there was "flash-player which is a from control-panel plugin"

**Comment by AmrBinBashir** [comment] 2020-09-23 02:22
@jygzyc   Okay, I submitted a PR to fix, until it is approved, don't try to use `Tab` on results from control-panel-plugin.

The keybinding `Tab` autocompletes the path of folders or files into the search input so you can use the File-Browser plugin.
Control-panel results kinda don't have paths and thus would throw an error so I would try to avoid using `Tab` when a control-panel plugin is selected.

**Comment by jygzyc** [comment] 2020-09-23 02:26
@AmrBinBashir Okay, I see.  I would not use `Tab` until fixed it.

**Comment by oliverschwendener** [comment] 2020-09-23 08:29
Accidentally closed this issue. A bugfix will be available in the next release.

**Comment by oliverschwendener** [comment] 2020-09-23 08:29
Thanks @AmrBinBashir

**Comment by AmrBinBashir** [comment] 2020-10-03 16:24
This issue should be closed now since the issue is fixed in the latest update.

**Closed** 2020-10-05 11:25 UTC
Labels: bug
