### ISSUE TITLE
App icon doesn't work since 8.1.2

### ISSUE THREAD

**Issue by BryantShepherd** [oliverschwendener/ueli#202] opened 2019-10-03 03:21 UTC
![image](https://user-images.githubusercontent.com/42168740/66097138-7ecb0e00-e5c7-11e9-984d-84748edb2846.png)

**Comment by oliverschwendener** [comment] 2019-10-03 05:58
Thanks for the report! Will check this asap!

**Comment by BryantShepherd** [comment] 2019-10-03 06:31
Going back to 7.2.0 solves the problem. But after I update back to 8.1.3, the problem still persists. Hope this help 😔

**Comment by oliverschwendener** [comment] 2019-10-03 07:03
Is there something in the debug log?

![image](https://user-images.githubusercontent.com/15727229/66105763-a072c800-e5bc-11e9-8a7c-ae796eda1987.png)

**Comment by BryantShepherd** [comment] 2019-10-03 07:13
I will check it and post it here when I get home.

**Comment by BryantShepherd** [comment] 2019-10-03 08:20
[debug.log](https://github.com/oliverschwendener/ueli/files/3685068/debug.log)
Here it is.

**Comment by oliverschwendener** [comment] 2019-10-03 08:31
What happens if you clear all caches and den refresh the indexes?

![image](https://user-images.githubusercontent.com/15727229/66111300-dddd5280-e5c8-11e9-8a1a-7a60f812fe11.png)

![image](https://user-images.githubusercontent.com/15727229/66111312-e33a9d00-e5c8-11e9-9c4b-0115e6fcb85b.png)

**Comment by BryantShepherd** [comment] 2019-10-03 13:11
The bug is still here after I tried clearing the caches and refreshing the indexes :(

**Comment by oliverschwendener** [comment] 2019-10-03 15:45
For me it works fine. Can you show me the settings of the application search plugin?

**Comment by oliverschwendener** [comment] 2019-10-03 15:46
You probably disabled the option "Use native icons"

**Comment by BryantShepherd** [comment] 2019-10-03 16:09
![image](https://user-images.githubusercontent.com/42168740/66144235-a6a38b80-e632-11e9-8486-b0292b8de876.png)

I got this error when I tried turning on "Use native icon"
{ "level": "error", "name": "PS_CMD_FAIL_ERROR", "service": "user-service", "timestamp": "2019-10-03T16:06:52.914Z" }

**Comment by oliverschwendener** [comment] 2019-10-07 06:25
What happens if you reset the application search settings to default?

![image](https://user-images.githubusercontent.com/15727229/66289152-0ec8ca80-e8dc-11e9-91e7-d57d99587113.png)

**Comment by oliverschwendener** [comment] 2019-10-07 10:48
And does this issue occur in [8.1.1](https://github.com/oliverschwendener/ueli/releases/v8.1.1)?

**Comment by BryantShepherd** [comment] 2019-10-08 07:42
No, 8.1.1 is fine. I've been using it since I discovered the bug.

**Comment by oliverschwendener** [comment] 2019-10-08 07:51
What about resetting the settings to default?

**Comment by Cupbox** [comment] 2019-10-08 19:10
Had the same issue with the same error
{ "level": "error", "name": "PS_CMD_FAIL_ERROR", "service": "user-service", "timestamp": "2019-10-08T18:33:28.240Z" }
A particular shortcut seemed to be problematic and deleting it fixed it. Recreating the same shortcut did not throw any issues.

**Comment by oliverschwendener** [comment] 2019-10-10 06:54
@BryantShepherd Can you check if this is also the case for you?

**Comment by BryantShepherd** [comment] 2019-10-13 06:04
> What about resetting the settings to default?

It did fixed the issues by resetting "Application Search" to default. Thanks a lot!

**Comment by BryantShepherd** [comment] 2019-10-13 06:08
A path contains my pdf files seems to cause the problem. Every time I tried to readd it, the problem reemerges.

**Comment by oliverschwendener** [comment] 2019-10-13 06:36
Good to know, I'll look into it!

**Comment by oliverschwendener** [comment] 2019-10-13 20:15
Do you know which file extactly is causing the problem? I tried adding pdf to the extensions and it worked without any problems.

**Comment by BryantShepherd** [comment] 2019-10-14 00:43
![image](https://user-images.githubusercontent.com/42168740/66724938-25c86900-ee56-11e9-9137-5c194baa8b70.png)
Here is my pdf folder. I could only include this or include '.pdf' extension but not both. Maybe it's just my device has a problem, because my other pc works fine.

**Comment by oliverschwendener** [comment] 2019-10-14 07:03
Ok, then I'll close this issue now.

Just for clarification:
- Use the application search plugin only to search programs
- If you want to search specific folders use the simple folder search plugin
- If you want to search files on a global scope then use the everything plugin

**Closed by oliverschwendener** 2019-10-14 07:03 UTC
Labels: bug

**Comment by dolandemort** [comment] 2019-10-22 04:14
Can confirm that this is also an issue for me. I reproduced the issue by doing the following:

1. Added a directory that contains videos.
2. Added '.mkv' and '.mp4' extensions.

It is the combination of these two things that seems to cause the problems. Obviously that directory contains files of both these types.

**Comment by oliverschwendener** [comment] 2019-10-22 07:04
As stated in my previous comment:

> * Use the application search plugin only to search programs
> * If you want to search specific folders use the simple folder search plugin
> * If you want to search files on a global scope then use the everything plugin

**Comment by dolandemort** [comment] 2019-10-22 21:07
Oh, I see. Unfortunately, I and many others will elect not to install Everything since it isn't open source (one of the attractions of ueli for many).

**Comment by TheMechanical** [comment] 2019-11-27 19:39
Hmm. I got the same error when adding .lnk extension on Windows 10. 
ueli 8.3.0

`{"level": "error", "name": "PS_CMD_FAIL_ERROR", "service": "user-service", "timestamp": "2019-11-27T19: 31: 41.397Z"}`

There are no icons :(

![image](https://user-images.githubusercontent.com/20208434/69754071-0bc4ba80-1166-11ea-97f0-de7028473815.png)

I tried all of the above. Does not work

**Comment by oliverschwendener** [comment] 2019-11-27 21:35
Can you post a screenshot of your application search settings?

**Comment by BryantShepherd** [comment] 2019-11-27 23:20
The problem is solved when I update to version 8.2.0. Thanks very much!

**Comment by TheMechanical** [comment] 2019-11-28 06:19
> Can you post a screenshot of your application search settings?

Hi. Settings by default:

![image](https://user-images.githubusercontent.com/20208434/69781655-d2b93400-11bf-11ea-8f14-cbc4312a13fc.png)

Turns the "Use native icons" setting on and off.
When the setting is on, an error occurs; when it is turned off, there is no error. But there are no application icons in both cases.

**Comment by TheMechanical** [comment] 2019-12-04 14:56
So, I have found a problem. And she ended up in Windows 10.

In "executeCommandWithOutput" in "application-searcher.ts" PowerShell is used and it gave Cyrillic characters in the form of question marks (like this: ????-filename).

If someone has a similar problem. For the solution, you just need to fix the encoding in PowerShell:

In path: _C:\Users\{UserName}\Documents\WindowsPowerShell_

Created the file: _Microsoft.PowerShell_profile.ps1_

With this content:
`$ OutputEncoding = [console] :: InputEncoding = [console] :: OutputEncoding = New-Object System.Text.UTF8Encoding
`

Now the icons are displayed correctly.

**Comment by AmrBinBashir** [comment] 2019-12-22 19:19
@TheMechanical the code you provieded didn't work for me first because the execution policy on my machine was Restricted and secondly your code had some errors, here is the code that worked for me
`$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding`

**Comment by oliverschwendener** [comment] 2020-01-04 10:27
I added a fix in the newest version. Can you guys check if it works now?

1. Clear caches first:
![image](https://user-images.githubusercontent.com/15727229/71764210-24eb2480-2ee5-11ea-8882-56231cab10c6.png)

2. Then refresh indices:
![image](https://user-images.githubusercontent.com/15727229/71764215-30d6e680-2ee5-11ea-85b6-a3d494f5ebed.png)
