### ISSUE TITLE
Being able to use Crtl+Win as the launch hotkey

### ISSUE THREAD

**Issue by Dalfons0** [oliverschwendener/ueli#796] opened 2021-09-10 15:27 UTC
Hi,

I use to work with a similar tool on linux and I found this tool, which looks pretty promising, but I feel that the hotkey launch options are too restrictive. For example, on linux I use the `Ctrl + Super` shortcut to launch the program but here I can't use the "windows" key with another modifier key. Is there any posibility to configure the tool to be able to use this hotkey?

**Comment by oliverschwendener** [comment] 2021-09-19 17:27
Maybe a duplicate of #454?

**Comment by oliverschwendener** [comment] 2024-04-20 09:20
Duplicate of #454

**Closed by oliverschwendener** 2024-04-20 09:20 UTC
Labels: enhancement
