### ISSUE TITLE
Web search

### ISSUE THREAD

**Issue by mylo17** [oliverschwendener/ueli#440] opened 2020-06-17 10:36 UTC
I have the google web search set up as fallback, but after writing 32 charcaters it just shows applications on my computer and interrupts any serach i was doing 

snapshot to better understand, before and after 32 characters:
https://imgur.com/a/xsC8Z5z

**Comment by oliverschwendener** [comment] 2020-06-22 14:21
Not sure if this is a bug. When setting up a web search engine as "fallback" it shows up when no other search results are found. Apparently there are search results found when you use a longer search term (in your case 32 characters). So in my opinion this is intended behavior. You can adjust the search engine's strictness in the search engine settings under "Fuzzyness", so that it does not find search results with a rather unprecise search term.

![image](https://user-images.githubusercontent.com/15727229/85298340-40061c80-b4a4-11ea-93f4-fb013aa1e823.png)

**Comment by Mylo17** [comment] 2020-06-24 14:03
negative , I have tried changing the fuzzyness to multiple values but the result was always the same

**Comment by oliverschwendener** [comment] 2020-06-25 09:40
Ok, this looks really like a bug. I'll look into this asap.

**Comment by Mylo17** [comment] 2020-06-25 12:35
thank you for the great job

**Comment by oliverschwendener** [comment] 2024-05-14 17:51
I assume that this will be fixed with ueli v9 as the web search results wont be mixed with indexed search results. You can try it out here: https://github.com/oliverschwendener/ueli/releases
If this is still an issue, feel free to reopen.

**Closed by oliverschwendener** 2024-05-14 17:51 UTC
Labels: bug
