### ISSUE TITLE
Network folders not accessable

### ISSUE THREAD

**Issue by dwerne** [oliverschwendener/ueli#199] opened 2019-09-26 14:27 UTC
Hi Oliver

is there a way to open a network folder like
\\servername\folder1\folder2\?
I tried with SHORTCUTS, but it didn't work.

thanks

**Comment by oliverschwendener** [comment] 2019-09-26 14:28
Closing this because it's a duplicate of #189

**Closed by oliverschwendener** 2019-09-26 14:28 UTC
